In [1]:
import pandas as pd
import requests

In [15]:
response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=80b5dc1eaf21d959f6203af6c02c0d58&&language=en-US&page=1')

In [17]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/xugEpZk9YQ0DIz1aFvH5HGkqpZK.jpg',
   'genre_ids': [27, 9648],
   'id': 1304313,
   'title': "Lee Cronin's The Mummy",
   'original_language': 'en',
   'original_title': "Lee Cronin's The Mummy",
   'overview': 'The young daughter of a journalist disappears into the desert without a trace—eight years later, the broken family is shocked when she is returned to them, as what should be a joyful reunion turns into a living nightmare.',
   'popularity': 594.6636,
   'poster_path': '/uIb9Tvae5haF0XcQBaPyufmxbb0.jpg',
   'release_date': '2026-04-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.072,
   'vote_count': 1367},
  {'adult': False,
   'backdrop_path': '/dd31qJxOarrHyGZwYsCzOjobQzP.jpg',
   'genre_ids': [28, 53],
   'id': 1380291,
   'title': "Tom Clancy's Jack Ryan: Ghost War",
   'original_language': 'en',
   'original_title': "Tom Clancy's Jack Ryan: Ghost War",
   'overview': 'Jack Ryan is reluctantly pulled back into espionage when an international covert mission unravels a deadly conspiracy. Racing against time, he joins CIA allies Mike November & James Greer and sharp MI6 officer Emma Marlowe to battle a rogue black-ops unit in a high-stakes, deeply personal fight.',
   'popularity': 399.0769,
   'poster_path': '/8ehYxUh5MWE41AeE9gkHE8DKzvB.jpg',
   'release_date': '2026-05-20',
   'softcore': False,
   'video': False,
   'vote_average': 7.233,
   'vote_count': 374},
  {'adult': False,
   'backdrop_path': '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg',
   'genre_ids': [27],
   'id': 1339713,
   'title': 'Obsession',
   'original_language': 'en',
   'original_title': 'Obsession',
   'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
   'popularity': 399.8813,
   'poster_path': '/6X4qFYBsG3bpWDG2XIKqr04kFJa.jpg',
   'release_date': '2026-05-13',
   'softcore': False,
   'video': False,
   'vote_average': 7.9,
   'vote_count': 343},
  {'adult': False,
   'backdrop_path': '/qO55CD8tgVL1T4WKn6zYFFiD6lL.jpg',
   'genre_ids': [28, 18, 80],
   'id': 1439930,
   'title': 'The Punisher: One Last Kill',
   'original_language': 'en',
   'original_title': 'The Punisher: One Last Kill',
   'overview': 'As Frank Castle searches for meaning beyond revenge, an unexpected force pulls him back into the fight.',
   'popularity': 319.3487,
   'poster_path': '/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg',
   'release_date': '2026-05-12',
   'softcore': False,
   'video': False,
   'vote_average': 8.39,
   'vote_count': 1308},
  {'adult': False,
   'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 270.6206,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 4321},
  {'adult': False,
   'backdrop_path': '/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg',
   'genre_ids': [10751, 35, 12, 14, 16],
   'id': 1226863,
   'title': 'The Super Mario Galaxy Movie',
   'original_language': 'en',
   'original_title': 'The Super Mario Galaxy Movie',
   'overview': "Having thwarted Bowser's previous plot to marry Princess Peach, Mario and Luigi now face a fresh threat in Bowser Jr., who is determined to liberate his father from captivity and restore the family legacy. Alongside companions new and old, the brothers travel across the stars to stop the young heir's crusade.",
   'popularity': 291.6036,
   'poster_path': '/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
   'release_date': '2026-04-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.043,
   'vote_count': 2080},
  {'adult': False,
   'backdrop_path': '/gRoZG3Z0zJxgElmTsVHOl2dNYXe.jpg',
   'genre_ids': [28, 80, 53],
   'id': 1582770,
   'title': 'Dhurandhar: The Revenge',
   'original_language': 'hi',
   'original_title': 'धुरंधर: द रिवेंज',
   'overview': "As rival gangs, corrupt officials and a ruthless Major Iqbal close in, Hamza's mission for his country spirals into a bloody personal war where the line between patriot and monster disappears in the streets of Lyari.",
   'popularity': 275.6895,
   'poster_path': '/ov8vrRLZGoXHpYjSY9Vpv1tHJX7.jpg',
   'release_date': '2026-03-18',
   'softcore': False,
   'video': False,
   'vote_average': 7.3,
   'vote_count': 95},
  {'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 270.0947,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 9.0,
   'vote_count': 1468},
  {'adult': False,
   'backdrop_path': '/1x9e0qWonw634NhIsRdvnneeqvN.jpg',
   'genre_ids': [10749, 18],
   'id': 1523145,
   'title': 'Your Heart Will Be Broken',
   'original_language': 'ru',
   'original_title': 'Твоё сердце будет разбито',
   'overview': 'High school student Polina is saved from bullying at her new school and makes a deal with the main bully Bars: he must pretend to be her boyfriend and protect her, and she must do everything he says. During this game, the couple develops real feelings, but her family and classmates have reasons to separate the lovers.',
   'popularity': 250.2719,
   'poster_path': '/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg',
   'release_date': '2026-03-26',
   'softcore': False,
   'video': False,
   'vote_average': 6.784,
   'vote_count': 81},
  {'adult': False,
   'backdrop_path': '/eNAFLrd1XAAD4hgdTPjewpzYU4W.jpg',
   'genre_ids': [35],
   'id': 1320660,
   'title': 'Pati Patni Aur Woh Do',
   'original_language': 'hi',
   'original_title': 'पति पत्नी और वो दो',
   'overview': 'A seemingly perfect marriage in Prayagraj takes an unexpected turn when one decision leads to a chain of misunderstandings, suspicion, and comedic chaos.',
   'popularity': 198.273,
   'poster_path': '/x0RUPvba4JlCCkyyEZGlQFIFVuF.jpg',
   'release_date': '2026-05-15',
   'softcore': False,
   'video': False,
   'vote_average': 7.5,
   'vote_count': 4},
  {'adult': False,
   'backdrop_path': '/oUozq2XHWifwAVOoS1qHU0qfXqM.jpg',
   'genre_ids': [27, 9648, 878],
   'id': 1083381,
   'title': 'Backrooms',
   'original_language': 'en',
   'original_title': 'Backrooms',
   'overview': 'A strange doorway appears in the basement of a furniture showroom.',
   'popularity': 187.0112,
   'poster_path': '/vpkNMkbisv5cTaIfCzUduYzXnjb.jpg',
   'release_date': '2026-05-27',
   'softcore': False,
   'video': False,
   'vote_average': 6.5,
   'vote_count': 87},
  {'adult': False,
   'backdrop_path': '/4EAAwpylq313qrDqpCxulUrXBNF.jpg',
   'genre_ids': [28, 14, 12],
   'id': 931285,
   'title': 'Mortal Kombat II',
   'original_language': 'en',
   'original_title': 'Mortal Kombat II',
   'overview': 'The fan favorite champions—now joined by Johnny Cage himself—are pitted against one another in the ultimate, no-holds barred, gory battle to defeat the dark rule of Shao Kahn that threatens the very existence of the Earthrealm and its defenders.',
   'popularity': 164.3456,
   'poster_path': '/lIsMeDbwntNXSUVHmWMMRXEZOVc.jpg',
   'release_date': '2026-05-06',
   'softcore': False,
   'video': False,
   'vote_average': 6.768,
   'vote_count': 330},
  {'adult': False,
   'backdrop_path': '/4VrLojD6Gl1HQkcDHAoHQjSDPh9.jpg',
   'genre_ids': [28, 12, 878],
   'id': 1228710,
   'title': 'The Mandalorian and Grogu',
   'original_language': 'en',
   'original_title': 'The Mandalorian and Grogu',
   'overview': 'The evil Empire has fallen, and Imperial warlords remain scattered throughout the galaxy. As the fledgling New Republic works to protect everything the Rebellion fought for, they have enlisted the help of legendary Mandalorian bounty hunter Din Djarin and his young apprentice Grogu.',
   'popularity': 179.8917,
   'poster_path': '/5Vi8dSauVwH1HOsiZceDMbRr1Ca.jpg',
   'release_date': '2026-05-20',
   'softcore': False,
   'video': False,
   'vote_average': 6.8,
   'vote_count': 308},
  {'adult': False,
   'backdrop_path': '/7f9ZaTwyqQOJtNWUS7xZgWQOzSt.jpg',
   'genre_ids': [53],
   'id': 1431071,
   'title': 'System',
   'original_language': 'hi',
   'original_title': 'सिस्टम',
   'overview': 'When Neha Rajvansh, a privileged public prosecutor, meets Sarika Rawat, a courtroom stenographer from a humble background, their lives are thrown into upheaval where power defines truth, blurring the system and raising a question of what justice truly means to them.',
   'popularity': 137.9909,
   'poster_path': '/8qrddM5BRcTuqjc9crJY6e3gyE6.jpg',
   'release_date': '2026-05-22',
   'softcore': False,
   'video': False,
   'vote_average': 7.5,
   'vote_count': 2},
  {'adult': False,
   'backdrop_path': '/kkRpcauZoBFKnH0Qsy7J5qtwBF5.jpg',
   'genre_ids': [10749, 18],
   'id': 1371023,
   'title': 'Chand Mera Dil',
   'original_language': 'hi',
   'original_title': 'चाँद मेरा दिल',
   'overview': "Aarav and Chandni's passionate college romance is struck by adulthood far too soon, forcing the two young lovers to balance their ambitions with responsibility and realize the evolved meaning of love.",
   'popularity': 196.1546,
   'poster_path': '/9LPkXJustudEBgPZEm9tgDx5KtC.jpg',
   'release_date': '2026-05-22',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/6ELCZlTA5lGUops70hKdB83WJxH.jpg',
   'genre_ids': [28, 14, 12],
   'id': 460465,
   'title': 'Mortal Kombat',
   'original_language': 'en',
   'original_title': 'Mortal Kombat',
   'overview': "Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.",
   'popularity': 155.7634,
   'poster_path': '/ybrX94xQm8lXYpZAPRmwD9iIbWP.jpg',
   'release_date': '2021-04-07',
   'softcore': False,
   'video': False,
   'vote_average': 7.033,
   'vote_count': 6658},
  {'adult': False,
   'backdrop_path': '/gkh6Nt8DtY1XT4gQsyFq9XAVJlJ.jpg',
   'genre_ids': [18, 35],
   'id': 350,
   'title': 'The Devil Wears Prada',
   'original_language': 'en',
   'original_title': 'The Devil Wears Prada',
   'overview': 'A young woman from the Midwest gets more than she bargained for when she moves to New York to become a writer and ends up as the assistant to the tyrannical, larger-than-life editor-in-chief of a major fashion magazine.',
   'popularity': 152.1336,
   'poster_path': '/8912AsVuS7Sj915apArUFbv6F9L.jpg',
   'release_date': '2006-06-29',
   'softcore': False,
   'video': False,
   'vote_average': 7.424,
   'vote_count': 13595},
  {'adult': False,
   'backdrop_path': '/4BtL2vvEufDXDP4u6xQjjQ1Y2aT.jpg',
   'genre_ids': [28, 80, 18, 53],
   'id': 1419406,
   'title': "The Shadow's Edge",
   'original_language': 'zh',
   'original_title': '捕风追影',
   'overview': 'Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves.',
   'popularity': 154.8103,
   'poster_path': '/cHKo3m8N1fwvEy2ZEr0xGmmMODV.jpg',
   'release_date': '2025-08-16',
   'softcore': False,
   'video': False,
   'vote_average': 7.399,
   'vote_count': 696},
  {'adult': False,
   'backdrop_path': '/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg',
   'genre_ids': [12, 16, 35, 10751, 878],
   'id': 1327819,
   'title': 'Hoppers',
   'original_language': 'en',
   'original_title': 'Hoppers',
   'overview': "Scientists have discovered how to 'hop' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.",
   'popularity': 142.3815,
   'poster_path': '/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg',
   'release_date': '2026-03-04',
   'softcore': False,
   'video': False,
   'vote_average': 8.144,
   'vote_count': 1280},
  {'adult': False,
   'backdrop_path': '/rHnANzYUmV3WZw3n0yWOLiR3pen.jpg',
   'genre_ids': [53, 80],
   'id': 976912,
   'title': 'Graphic Desires',
   'original_language': 'en',
   'original_title': 'Graphic Desires',
   'overview': 'When reclusive Franklin cheats on his partner with a mysterious girl he meets on a dating app, it becomes the start of a deadly obsession.',
   'popularity': 142.2487,
   'poster_path': '/3BjLdTWRiHc1ISIZMFvToOmghOM.jpg',
   'release_date': '2023-08-31',
   'softcore': False,
   'video': False,
   'vote_average': 7.039,
   'vote_count': 76}],
 'total_pages': 57117,
 'total_results': 1142336}

In [19]:
df=pd.DataFrame(response.json()['results'])

In [21]:
df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/xugEpZk9YQ0DIz1aFvH5HGkqpZK.jpg,"[27, 9648]",1304313,Lee Cronin's The Mummy,en,Lee Cronin's The Mummy,The young daughter of a journalist disappears ...,594.6636,/uIb9Tvae5haF0XcQBaPyufmxbb0.jpg,2026-04-15,False,False,8.072,1367
1,False,/dd31qJxOarrHyGZwYsCzOjobQzP.jpg,"[28, 53]",1380291,Tom Clancy's Jack Ryan: Ghost War,en,Tom Clancy's Jack Ryan: Ghost War,Jack Ryan is reluctantly pulled back into espi...,399.0769,/8ehYxUh5MWE41AeE9gkHE8DKzvB.jpg,2026-05-20,False,False,7.233,374
2,False,/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg,[27],1339713,Obsession,en,Obsession,"After breaking the mysterious ""One Wish Willow...",399.8813,/6X4qFYBsG3bpWDG2XIKqr04kFJa.jpg,2026-05-13,False,False,7.900,343
3,False,/qO55CD8tgVL1T4WKn6zYFFiD6lL.jpg,"[28, 18, 80]",1439930,The Punisher: One Last Kill,en,The Punisher: One Last Kill,As Frank Castle searches for meaning beyond re...,319.3487,/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg,2026-05-12,False,False,8.390,1308
4,False,/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,270.6206,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.600,4321

In [24]:
df=pd.DataFrame(response.json()['results'])[['id','title','overview','original_title','release_date','vote_average','vote_count']]

In [25]:
df

,id,title,overview,original_title,release_date,vote_average,vote_count
0,1304313,Lee Cronin's The Mummy,The young daughter of a journalist disappears ...,Lee Cronin's The Mummy,2026-04-15,8.072,1367
1,1380291,Tom Clancy's Jack Ryan: Ghost War,Jack Ryan is reluctantly pulled back into espi...,Tom Clancy's Jack Ryan: Ghost War,2026-05-20,7.233,374
2,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...",Obsession,2026-05-13,7.900,343
3,1439930,The Punisher: One Last Kill,As Frank Castle searches for meaning beyond re...,The Punisher: One Last Kill,2026-05-12,8.390,1308
4,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,Project Hail Mary,2026-03-15,8.600,4321
5,1226863,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,The Super Mario Galaxy Movie,2026-04-01,8.043,2080
6,1582770,Dhurandhar: The Revenge,"As rival gangs, corrupt officials and a ruthle...",धुरंधर: द रिवेंज,2026-03-18,7.300,95
7,1007757,Swapped,"A small woodland creature and a majestic bird,...",Swapped,2026-05-01,9.000,1468
8,1523145,Your Heart Will Be Broken,High school student Polina is saved from bully...,Твоё сердце будет разбито,2026-03-26,6.784,81
9,1320660,Pati Patni Aur Woh Do,A seemingly perfect marriage in Prayagraj take...,पति पत्नी और वो दो,2026-05-15,7.500,4
10,1083381,Backrooms,A strange doorway appears in the basement of a...,Backrooms,2026-05-27,6.500,87
11,931285,Mortal Kombat II,The fan favorite champions—now joined by Johnn...,Mortal Kombat II,2026-05-06,6.768,330
12,1228710,The Mandalorian and Grogu,"The evil Empire has fallen, and Imperial warlo...",The Mandalorian and Grogu,2026-05-20,6.800,308
13,1431071,System,"When Neha Rajvansh, a privileged public prosec...",सिस्टम,2026-05-22,7.500,2
14,1371023,Chand Mera Dil,Aarav and Chandni's passionate college romance...,चाँद मेरा दिल,2026-05-22,0.000,0
15,460465,Mortal Kombat,"Washed-up MMA fighter Cole Young, unaware of h...",Mortal Kombat,2021-04-07,7.033,6658
16,350,The Devil Wears Prada,A young woman from the Midwest gets more than ...,The Devil Wears Prada,2006-06-29,7.424,13595
17,1419406,The Shadow's Edge,Macau Police brings the tracking expert police...,捕风追影,2025-08-16,7.399,696
18,1327819,Hoppers,Scientists have discovered how to 'hop' human ...,Hoppers,2026-03-04,8.144,1280
19,976912,Graphic Desires,When reclusive Franklin cheats on his partner ...,Graphic Desires,2023-08-31,7.039,76

In [26]:
df.tail(4)

,id,title,overview,original_title,release_date,vote_average,vote_count
16,350,The Devil Wears Prada,A young woman from the Midwest gets more than ...,The Devil Wears Prada,2006-06-29,7.424,13595
17,1419406,The Shadow's Edge,Macau Police brings the tracking expert police...,捕风追影,2025-08-16,7.399,696
18,1327819,Hoppers,Scientists have discovered how to 'hop' human ...,Hoppers,2026-03-04,8.144,1280
19,976912,Graphic Desires,When reclusive Franklin cheats on his partner ...,Graphic Desires,2023-08-31,7.039,76

In [27]:
empty_df=pd.DataFrame()
empty_df

Empty DataFrame
Columns: []
Index: []

In [31]:
for i in range(1,429):
    response=requests.get(f'https://api.themoviedb.org/3/movie/popular?api_key=80b5dc1eaf21d959f6203af6c02c0d58&&language=en-US&page={i}')
    temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','original_title','release_date','vote_average','vote_count']]
    empty_df=pd.concat([empty_df,temp_df],ignore_index=True)

In [32]:
empty_df

,id,title,overview,original_title,release_date,vote_average,vote_count
0,1304313,Lee Cronin's The Mummy,The young daughter of a journalist disappears ...,Lee Cronin's The Mummy,2026-04-15,8.072,1367
1,1380291,Tom Clancy's Jack Ryan: Ghost War,Jack Ryan is reluctantly pulled back into espi...,Tom Clancy's Jack Ryan: Ghost War,2026-05-20,7.233,374
2,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...",Obsession,2026-05-13,7.900,343
3,1439930,The Punisher: One Last Kill,As Frank Castle searches for meaning beyond re...,The Punisher: One Last Kill,2026-05-12,8.390,1308
4,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,Project Hail Mary,2026-03-15,8.600,4321
...,...,...,...,...,...,...,...
8935,336560,Lake Placid vs. Anaconda,A giant alligator goes head to head with a gia...,Lake Placid vs. Anaconda,2015-04-25,5.000,242
8936,462743,Suddenly Twenty,"After taking a magical picture, an elderly wom...",20 ใหม่ ยูเทิร์นวัย หัวใจรีเทิร์น,2016-11-24,7.000,15
8937,50237,Tarzoon: Shame of the Jungle!,"Shame, the ape man of the jungle, is aghast wh...",La Honte de la jungle,1975-09-04,5.900,106
8938,522406,Flashback,Frederick Fitzell is living his best life—unti...,Flashback,2021-06-03,6.000,329
8939,17130,Crossroads,"After eight years apart, three childhood frien...",Crossroads,2002-02-15,5.205,683

In [33]:
empty_df.shape

(8940, 7)

In [34]:
empty_df.to_csv('movies.csv',index=False)